apiVersion: v1
kind: Service
metadata:
  name: portfolio-website
  labels:
    app: portfolio-website
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: portfolio-website
  type: ClusterIP
